### ISSUE TITLE
[nebula-operator cannot set the annotations of service] nebula-operator中没有处理service里面的annotations，没办法增加自定义的label到service的annotations里面

### ISSUE THREAD

**Issue by woaiwah** [vesoft-inc/nebula-operator#113]

**Comment by veezhang** [comment]
@woaiwah 
Emm, thanks for your feedback, there is indeed no assignment here. Can you try to help submit a pr?

https://github.com/vesoft-inc/nebula-operator/blob/master/apis/apps/v1alpha1/nebulacluster_common.go#L413-L421

**Comment by woaiwah** [comment]
@veezhang 
So sorry！I don't know much about go language. I hope you can help solve this problem

**Comment by woaiwah** [comment]
@veezhang Line 383, func generateService(c NebulaClusterComponentter) *corev1.Service

**Comment by veezhang** [comment]
@woaiwah 
Thanks, we're going to fix it.
If you are in a hurry,  you can create a new service and then set `annotations` to it . Not sure if this can help you?

**Comment by veezhang** [comment]
@woaiwah 
What are you setting annotations for? I'll see if I can help you.

**Comment by woaiwah** [comment]
The internal k8s cluster of our company is managed by the operation and maintenance department. When I use k8s cluster deployment，I need to add a customized annotation of the operation and maintenance department, so as to comply with their rules. So i need to setting annotations in service

**Comment by veezhang** [comment]
@woaiwah Emm, you must set the annotations for all the service ?

**Comment by woaiwah** [comment]
> 



> @woaiwah Emm, you must set the annotations for all the service ?

Yes，deployment nebula-cluster，only graphd-svc needs

**Comment by veezhang** [comment]
@woaiwah Can you add an new service `xxx-graphd-svc-new` with the annotations?

**Comment by woaiwah** [comment]
> similar to exposing, making it accessible to the outside kubernetes

Yes , you are right，Now I'm try to add an new service nebula-graphd-svc-new with the annotations, I  don't know if I can succeed，This way will make graphd have two service。 Let me try。

**Comment by veezhang** [comment]
> > similar to exposing, making it accessible to the outside kubernetes
> 
> Yes , you are right，Now I'm try to add an new service nebula-graphd-svc-new with the annotations, I don't know if I can succeed，This way will make graphd have two service。 Let me try。
@woaiwah 
Emm, Two Services are fully allowed. You can try it out and contact us if you need support.

**Comment by woaiwah** [comment]
> You can try it out and contact us if you need support
Follow the above method，Two Services，and It can be used normally

**Comment by woaiwah** [comment]
> Follow the above method，Two Services，and It can be used normally

Follow the above method，Two Services，and It can be used normally
