### ISSUE TITLE
Application practice optimization suggestions for building Nebula clusters in Aliyun cloud

### ISSUE THREAD

**Issue by SevenLM361** [vesoft-inc/nebula-operator#114]
Hi, Nebula-operator Dev Team:
    When I was using nebula-operator recently, I found a rather interesting place.
    Currently nebula-operator only supportsthe storageClassName to create storage dynamically, when I practice building clusters on the cloud. AliCloud provides local storage (NVMe SSD) ECS to save half of the build cost when I creating a container cluster, and in my scenario I was able to get an additional 2TB of cloud disk space on this cluster. 
    However, the nebula-operator needs to provide a mechanism for setting up PVCs for the services, otherwise it will not be possible to configure existing PVs.

**Comment by MegaByte875** [comment]
Yes, nebula-operator doesn't support configure existing PV for each component. More accurately, local storage is not supported either.
