### ISSUE TITLE
Log rotation best practices for nebulaCuster pods

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-operator#115]
Dear Team,
May I know if there is already some mechanism to enable log rotation/ old files truncation?

Thanks!

**Comment by MegaByte875** [comment]
Hello @wey-gu 
Operator doesn't provide any log rotation tools,  we prefer nebulagraph support it.

**Comment by wey-gu** [comment]
from 3.0, nebula graph supports naming files with timestamps, and in baremetal cases, this would enable `logrotate` in Debian or centos from OS level.

While, in cloud-native case, corresponding can only be taken care by k8s layer I think.

ref: https://github.com/vesoft-inc/nebula/pull/3541/files

**Comment by MegaByte875** [comment]
Right, I think provide a log rotater sidecar container could resolve it.

**Comment by wey-gu** [comment]
ref:
- https://vividcode.io/enable-log-rotation-in-kubernetes-cluster/
- https://github.com/mkilchhofer/logrotate-container

**Comment by MegaByte875** [comment]
#179

**Comment by wey-gu** [comment]
You are amazing @MegaByte875
