### ISSUE TITLE
Link of "openkruise installation documentation" is invalid

### ISSUE THREAD

**Issue by showjason** [vesoft-inc/nebula-operator#120]
I find the link of `openkruise installation documentation` in [Installing Add-ons ](https://github.com/vesoft-inc/nebula-operator/blob/master/doc/user/add-ons.md)is redirect to `Page Not Found`
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/27723125/157828454-4c4b0033-8adb-4689-9019-294abf1a32d0.png">

**Comment by MegaByte875** [comment]
Thank you @showjason, we will fix it.
