### ISSUE TITLE
storage pod not ready until manually running `add host storageip:por`

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula-operator#125]
Before executing the `add hosts` command, the storage pod status kept showing not ready.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/78209557/163300485-e517e4eb-95b7-434a-970b-a6addfb9195d.png">

![image](https://user-images.githubusercontent.com/78209557/163184077-a6d182c8-1d15-41c0-81c1-c344a3a6389e.png)

After executing  `add hosts` manually, the storage pod status shows `ready`.
 
![image](https://user-images.githubusercontent.com/78209557/163184336-a88bff84-b8c0-4a1d-9084-87848ef1428f.png)
![image](https://user-images.githubusercontent.com/78209557/163184401-92667ee9-9bd3-427b-bf6c-3c414e027764.png)

**Comment by MegaByte875** [comment]
![image](https://user-images.githubusercontent.com/4974026/163672200-3884d2ce-6632-4a0f-ba8f-e18be34a09cb.png)
@abby-cyber  I tested it by helm, but I did't recur it.

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
