### ISSUE TITLE
GraphService.cpp:228] Unknown auth type:

### ISSUE THREAD

**Issue by dockerxu123** [vesoft-inc/nebula-operator#126]
集群运行环境：nebula-operator 1.0.0   nebula-graphd 3.0.2
[root@k8s-master1 ~]# kubectl get pod -n kube-nebula
NAME                                                            READY   STATUS    RESTARTS   AGE
nebula-graphd-0                                                 1/1     Running   0          34m
nebula-metad-0                                                  1/1     Running   0          29m
nebula-operator-controller-manager-deployment-79fb98f94-pbfj7   2/2     Running   0          76m
nebula-operator-controller-manager-deployment-79fb98f94-vk98s   2/2     Running   2          5h7m
nebula-operator-scheduler-deployment-7898449b87-469zx           2/2     Running   1          5h7m
nebula-operator-scheduler-deployment-7898449b87-blpxw           2/2     Running   2          5h7m
nebula-storaged-0                                               1/1     Running   1          46m
nebula-storaged-1                                               1/1     Running   1          46m
nebula-storaged-2                                               1/1     Running   1          46m

客户端连接日志ba报错
![1649927696(1)](https://user-images.githubusercontent.com/81321790/163354020-75329ade-c181-4fc5-a357-5788ce45a78a.png)

nebula-graphd日志报错：
![1649927740(1)](https://user-images.githubusercontent.com/81321790/163354143-2c3f2509-a8e0-4ffa-8777-76ec8d88830e.png)
![1649927790(1)](https://user-images.githubusercontent.com/81321790/163354281-5ee67380-831c-4194-80be-243586e4196e.png)

**Comment by MegaByte875** [comment]
![image](https://user-images.githubusercontent.com/4974026/163671328-6e2ce56a-f4bb-4bc6-a040-b0e0b3ed1e02.png)
@dockerxu123 I tested in power shell

**Comment by dockerxu123** [comment]
我容器也运行正常的啊连接就是报错
![1650105383(1)](https://user-images.githubusercontent.com/81321790/163671742-69574bdc-530d-4795-a3e6-8298fda85a52.png)
![1650105551(1)](https://user-images.githubusercontent.com/81321790/163671800-71502017-7fb1-4e8e-bfd4-bcca84bde4ff.png)

**Comment by dockerxu123** [comment]
yaml文件如下：
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaCluster
metadata:
  name: nebula
spec:
  graphd:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    replicas: 1
    image: vesoft/nebula-graphd
    version: v3.0.2
    service:
      type: NodePort
      externalTrafficPolicy: Local
    config:
      "enable_authorize": "true"
      "auth_type": "5Y7WCg9IGzYNf"
    logVolumeClaim:
      resources:
        requests:
          storage: 4Gi
      storageClassName: nfs-storage
  metad:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    replicas: 1
    image: vesoft/nebula-metad
    version: v3.0.2
    dataVolumeClaim:
      resources:
        requests:
          storage: 4Gi
      storageClassName: nfs-storage
    logVolumeClaim:
      resources:
        requests:
          storage: 4Gi
      storageClassName: nfs-storage
  storaged:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    replicas: 3
    image: vesoft/nebula-storaged
    version: v3.0.2
    dataVolumeClaim:
      resources:
        requests:
          storage: 4Gi
      storageClassName: nfs-storage
    logVolumeClaim:
      resources:
        requests:
          storage: 4Gi
      storageClassName: nfs-storage
  reference:
    name: statefulsets.apps
    version: v1
  schedulerName: default-scheduler
  imagePullPolicy: Always

**Comment by MegaByte875** [comment]
![image](https://user-images.githubusercontent.com/4974026/163672387-90bc9e16-0274-4241-b763-d8fcdb668142.png)
'auth_type' should set to --auth_type=password

**Comment by dockerxu123** [comment]
是这样？
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaCluster
metadata:
  name: nebula
spec:
  graphd:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    replicas: 1
    image: vesoft/nebula-graphd
    version: v3.0.2
    service:
      type: NodePort
      externalTrafficPolicy: Local
    config:
      "enable_authorize": "true"
      "auth_type": nebula
    logVolumeClaim:
      resources:
        requests:
          storage: 4Gi
      storageClassName: nfs-storage

**Comment by dockerxu123** [comment]
![Uploading 1650107827(1).png…]()
![Uploading 1650107871(1).png…]()
可以了谢谢 感谢

**Comment by dockerxu123** [comment]
2.6.2版本和3.0版本yaml文件不一样？我2.6.2向刚才那样写法没有问题

**Comment by dockerxu123** [comment]
感谢！！！！3Q
