### ISSUE TITLE
How can I change graphd service type to LoadBalancer? currently ClusterIp hardcoded

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula-operator#134]
Hi @wey-gu, how can we change graphd service type to LoadBalancer? currently ClusterIp hardcoded!

**Comment by wey-gu** [comment]
Dear @porscheme,

Nebula GraphClient/GraphD endpoint are load-balanced from the client-side, if you look into those clients, we specify all graphD addresses to the connetion_pool and it will round-robin from them.

To me, the load balancer/api gateway pattern cannot be applied to the nebula graph.

@MegaByte875 @veezhang @kqzh kindly add/correct if I understood it wrongly.

Thanks!

**Comment by porscheme** [comment]
nebula-operator:v1.1.0
Nebula version: v3.1.0
Helm Charts

- Client has to be with K8S cluster to reach graphd, since its using ClusterIP
- Also, below simple query taking 20 minutes, Any tips t-shoot slow response?
```
MATCH (s:Student)-[r]-(a:CourseTcode)-[rr]-(b)
WHERE a.CourseTcode.id == 522687
RETURN s, r, a, rr, b limit 3
```

**Comment by MegaByte875** [comment]
@porscheme [https://github.com/vesoft-inc/nebula-operator/tree/master/config/samples](url) we also provide graph-nodeport service and  nginx-ingress, you can have a try.

**Comment by wey-gu** [comment]
@porscheme 
> Client has to be with K8S cluster to reach graphd, since its using ClusterIP

Now I understood that you would like to expose its endpoint rather than questioning on load balancing part, we should create individual services per each graphD instance (as I mentioned above, client-side load balancing) as @MegaByte875 shared in the samples.

@MegaByte875, is it possible to provide those nodeport or ingress services per graphD by the operator itself? I believe this would be super helpful for users as the application layer in most cases is not in the same namespace or even cluster of NebulaClsuter.

**Comment by porscheme** [comment]
Thaanks @wey-gu & @MegaByte875.

- Our Spark & Nebula are in two different K8S cluster

> @porscheme https://github.com/vesoft-inc/nebula-operator/tree/master/config/samples we also provide graph-nodeport service and nginx-ingress, you can have a try.

Can you make this part of the helm chart?

**Comment by MegaByte875** [comment]
@wey-gu Yes, this can be a feature  @porscheme OK, I will make the service configurable by helm charts

**Comment by porscheme** [comment]
> @wey-gu Yes, this can be a feature @porscheme OK, I will make the service configurable by helm charts
This feature is very important for us to use Nebula-spark-connector, check with @wey-gu for more details.
This is blocking us.
Can we do this over this weekend, I can be your tester :)

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/147 @porscheme

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
