### ISSUE TITLE
Chart package missing config configuration item

### ISSUE THREAD

**Issue by kinghu88** [vesoft-inc/nebula-operator#135]
Chart package downloaded through helm pull, nebula cluster.yaml template is missing config configuration item

![image](https://user-images.githubusercontent.com/24669338/166864626-d3418ba3-b59e-4b37-8de3-ea037288fa15.png)
![image](https://user-images.githubusercontent.com/24669338/166864746-6a5eae49-422e-453f-b86a-50929eebf9a4.png)

**Comment by MegaByte875** [comment]
@kinghu88  can you commit a pr to fix it?

**Comment by MegaByte875** [comment]
I've checked nebula-cluster charts, config filelds exists,  if you have any questions about helm deployment,  please reopen the issue.
