### ISSUE TITLE
Scaling: `ADD HOSTS "foo-bar":9779` should be done by operator after scaling out

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-operator#143]
as titled.

**Comment by MegaByte875** [comment]
Yes, I've tested with community edition, it can be supported.

**Comment by wey-gu** [comment]
> Yes, I've tested with community edition, it can be supported.

Amazing, when will this PR be published/merged, please?

**Comment by jjsimps** [comment]
I can confirm that I needed to do the manual `ADD HOSTS ..` when I was adding more replicas to an existing deployment. One thing that I've currently run into though -- I am unable to distribute the data partitions as it seems like the `BALANCE DATA` command does not exist (or is enterprise-only?). It feels like there's something missing if I can scale it out but I can't re-balance the data. Or am I missing something? Do I need to maybe re-create the graph space?

**Comment by wey-gu** [comment]
> I can confirm that I needed to do the manual `ADD HOSTS ..` when I was adding more replicas to an existing deployment. One thing that I've currently run into though -- I am unable to distribute the data partitions as it seems like the `BALANCE DATA` command does not exist (or is enterprise-only?). It feels like there's something missing if I can scale it out but I can't re-balance the data. Or am I missing something? Do I need to maybe re-create the graph space?

Now we need to switch experimental flag on to enable balance function🫣.

**Comment by MegaByte875** [comment]
@jjsimps  https://github.com/vesoft-inc/nebula-operator/pull/151

**Comment by wey-gu** [comment]
Thanks @MegaByte875 , so we could close this as #151 being merged, right?

**Comment by MegaByte875** [comment]
@wey-gu  Yes, the issue can be closed.

**Comment by wey-gu** [comment]
Thanks!!! @MegaByte875
