### ISSUE TITLE
operator的弹性扩展疑问

### ISSUE THREAD

**Issue by YSH-19980902** [vesoft-inc/nebula-operator#144]
1.不只是提供一个简化部署运维的工具吗？能实现弹性扩展吗？
2.这里的弹性扩展是指仅仅扩展pod还是添加集群机器进行数据分散？
3.弹性扩展具体是根据什么实现的？raft协议吗？
4.我测试了下好像pod的扩展都无法进行。
能否写篇博客探讨一下

**Comment by wey-gu** [comment]
@MuYiYong @MegaByte875 for scaling in and out, I think 

a. `add hosts`/`remove hosts`
b.`data balance`/ `data remove` 

are both expected to be done by the operator(that's what the operator pattern is good at doing) :), what do you think?

**Comment by wey-gu** [comment]
> 4.我测试了下好像pod的扩展都无法进行。

For now, i.e. when doing a scale-out, after you changed a Storage replica number of nebulaCluster, you could do another `ADD HOSTS "xxx.domain.tld":yy` from console manually as the mitigation, it should be working fine. Of course, manually doing data balance is also required afterward.

**Comment by QingZ11** [comment]
@YSH-19980902 We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.
