### ISSUE TITLE
PVC has no label, and the operator cannot be started successfully

### ISSUE THREAD

**Issue by damuji8** [vesoft-inc/nebula-operator#149]
https://github.com/vesoft-inc/nebula-operator/blob/master/pkg/kube/pvc.go
We deploy the nebula operator in the local kubernetes cluster， pvc has no label, and the operator cannot be started successfully.
operator logs:  assignment to entry in nil map.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/31397673/187898125-e371b775-dbee-4f94-b571-89bd2d9b36f8.png">
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/31397673/187898194-2dcaea44-1ca7-4efa-ba6c-530696164c10.png">

here also need
if pvc.Labels == nil {
		pvc.Labels = make(map[string]string)
	}

**Comment by wey-gu** [comment]
Thanks @damuji8 for reporting this :), Are you interested in a PR to fix it? As you already find it down to the code line

**Comment by wey-gu** [comment]
@damuji8 we will reach out to you for a nebulagraph contributor souvenir and certificate :)

again, thanks a lot for the contribution and welcome to the nebulagraph community!
