### ISSUE TITLE
how to config the storage datapath multiple directories for datapath in storage.conf 

### ISSUE THREAD

**Issue by lipinbo** [vesoft-inc/nebula-operator#152]
How to configure multiple directories for datapath in storage.conf like a built entity cluster  in a nebula_cluster started  by operator

**Comment by MegaByte875** [comment]
@lipinbo operator don't support multi  datapath now, I will upgrade to support it recently, please keep eye on.

**Comment by lipinbo** [comment]
Thanks very much for answering questions, and I'm looking forward to the new version

**Comment by MegaByte875** [comment]
@lipinbo  https://github.com/vesoft-inc/nebula-operator/pull/157

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
