### ISSUE TITLE
lack of license configurations in chart files

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula-operator#153]
Please add license related configs for HELM CHART

https://github.com/vesoft-inc/nebula-operator/blob/master/charts/nebula-cluster/values.yaml

**Comment by MegaByte875** [comment]
@abby-cyber  https://github.com/vesoft-inc/nebula-operator/pull/157

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
