### ISSUE TITLE
Nebula operator annotations

### ISSUE THREAD

**Issue by robcinko** [vesoft-inc/nebula-operator#155]
Hi,

would be a possibility to add `podAnnotations:` for Nebula-operator in helm values.yaml file ?

Thanks

**Comment by MegaByte875** [comment]
@robcinko Of course we can,  I want to know what it's used for?

**Comment by robcinko** [comment]
We are scraping some metrics from operator-controller /metrics endpoint. Now we have to annotate this pods manually to be visible for our prometheus, and if pod is restarted we have to annotate pod again. 
Possibility to have annotations in values.yaml will be very helpful.

Thank you.

**Comment by MegaByte875** [comment]
@robcinko OK, we will support it.

**Comment by MegaByte875** [comment]
@robcinko We've supported it, [https://github.com/vesoft-inc/nebula-operator/blob/7ecf26fce2ace41802d9e05b530cb676dc57551f/apis/apps/v1alpha1/nebulacluster_types.go#L283](url)

**Comment by wey-gu** [comment]
> @robcinko We've supported it, [https://github.com/vesoft-inc/nebula-operator/blob/7ecf26fce2ace41802d9e05b530cb676dc57551f/apis/apps/v1alpha1/nebulacluster_types.go#L283](url)

amazing @MegaByte875

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
