### ISSUE TITLE
I need nebula-operator arch=linux/arm64 image

### ISSUE THREAD

**Issue by wylovejzj** [vesoft-inc/nebula-operator#156]
I need nebula-operator arch=linux/arm64 image, thanks!

**Comment by MegaByte875** [comment]
@wylovejzj OK, we will build arm64 image and push to docker hub.

**Comment by wylovejzj** [comment]
thanks!发自我的手机-------- 原始邮件 --------发件人： "kevin.qiao" ***@***.***>日期： 2022年9月26日周一 上午10:12收件人： vesoft-inc/nebula-operator ***@***.***>抄送： wangyue ***@***.***>, Mention ***@***.***>主    题： Re: [vesoft-inc/nebula-operator] I need nebula-operator arch=linux/arm64 image (Issue #156)
@wylovejzj OK, we will build arm64 image and push to docker hub.

**Comment by MegaByte875** [comment]
@wylovejzj  The image with latest tag has support arch linux/arm64.

**Comment by wylovejzj** [comment]
ok,thank you very much!发自我的手机-------- 原始邮件 --------发件人： "kevin.qiao" ***@***.***>日期： 2022年10月9日周日 傍晚5:50收件人： vesoft-inc/nebula-operator ***@***.***>抄送： wangyue ***@***.***>, Mention ***@***.***>主    题： Re: [vesoft-inc/nebula-operator] I need nebula-operator arch=linux/arm64 image (Issue #156)
@wylovejzj  The image with latest tag has support arch linux/arm64.

**Comment by JingbenShi668** [comment]
> @wylovejzj The image with latest tag has support arch linux/arm64.

Hi,  the  visit to the docker hub sometimes is unstable in china. Can you upload the docker artifacts to your Github Release just like redis-operator project in the link https://github.com/spotahome/redis-operator/releases ?
<img width="922" alt="image" src="https://user-images.githubusercontent.com/39040502/197396336-cb24214c-c706-4d71-8501-ad580651fa06.png">

**Comment by wey-gu** [comment]
> > @wylovejzj The image with latest tag has support arch linux/arm64.
> 
> 
> 
> Hi,  the  visit to the docker hub sometimes is unstable in china. Can you upload the docker artifacts to your Github Release just like redis-operator project in the link https://github.com/spotahome/redis-operator/releases ?
> 
> <img width="922" alt="image" src="https://user-images.githubusercontent.com/39040502/197396336-cb24214c-c706-4d71-8501-ad580651fa06.png">
> 
> 

could you plz try with some docker hub mirrors? 
I.E. https://yeasy.gitbook.io/docker_practice/install/mirror

**Comment by JingbenShi668** [comment]
> 

OK，it maybe a good way to achive docker images.

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
