### ISSUE TITLE
volume size reconcile support

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-operator#158]
It's reported that when we change the data size in CRD, it's not reflected in PV, could we add support on this?

**Comment by wey-gu** [comment]
> @wey-gu I think the feature need k8s support it, refer to [110522](https://github.com/kubernetes/kubernetes/pull/110522)

OK, I see, thanks @MegaByte875 !
I am surprised that this is not yet ready in k8s.

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
