### ISSUE TITLE
Install Operator failure

### ISSUE THREAD

**Issue by JingbenShi668** [vesoft-inc/nebula-operator#159]
As you can see in the below picture, I have attempted to install the nebula-operator with helm for many times. However, I always encounter this failure. I don't know why it happens?
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/39040502/197410614-7b55ce73-ae7a-4d3b-9cd2-0a37af302c32.png">

**Comment by JingbenShi668** [comment]
Maybe, should I install Add-ones before installing Operator?
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/39040502/197410879-507ef152-d6ab-4a70-88c8-546e04168a75.png">

**Comment by wey-gu** [comment]
> Maybe, should I install Add-ones before installing Operator?
> 
> <img width="1061" alt="image" src="https://user-images.githubusercontent.com/39040502/197410879-507ef152-d6ab-4a70-88c8-546e04168a75.png">
> 
> 

Yes, this error refers to very manager not being installed, you should install add-ons first.

**Comment by MegaByte875** [comment]
@JingbenShi668 You can run helm commad with  "--set  admissionWebhook.create=false" to ignore cert-manager

**Comment by wey-gu** [comment]
> @JingbenShi668 You can run helm commad with "--set admissionWebhook.create=false" to ignore cert-manager

Will that possible/reasonable to have `admissionWebhook.create=false` be default?

**Comment by MegaByte875** [comment]
@wey-gu The value is default false now.

**Comment by wey-gu** [comment]
> @wey-gu The value is default false now.

Great, so it's already changed to false by default in a version after 1.1.0 right?

**Comment by MegaByte875** [comment]
@wey-gu Yes

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
