### ISSUE TITLE
The minimum supported version of Kubernetes

### ISSUE THREAD

**Issue by verlocks** [vesoft-inc/nebula-operator#16]
In Install Guide, the minimum supported version of Kubernetes is 1.12. However, the add-on Cert-Manager v1.2.0 required the version of Kubernetes at least 1.16. And when I try to create a nebula cluster, it shows the error below:
`failed to install CRD crds/nebulacluster.yaml: unable to recognize "":no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"`

The version of my kubernetes server is 1.13, and I found that in [kubernetes document](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/), the minimum version to support CRD is 1.16. So what is the minimum supported version of Kubernetes actually? Can I use it with kubernetes v1.13?

**Comment by MegaByte875** [comment]
nebula-operator based on apiextensions v1,  it means that you need a k8s cluster the minimum is 1.16, we are not yet compatible with the lower version below 1.16.

**Comment by verlocks** [comment]
> nebula-operator based on apiextensions v1, it means that you need a k8s cluster the minimum is 1.16, we are not yet compatible with the lower version below 1.16.

Thanks for reply. Looks like the document needs to be revised.
