### ISSUE TITLE
Error while upgrading to 1.3

### ISSUE THREAD

**Issue by jjsimps** [vesoft-inc/nebula-operator#163]
When I upgrade to the latest version using helm upgrade I get the error:

`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(NebulaCluster.spec.storaged): unknown field "dataVolumeClaims" in io.nebula-graph.apps.v1alpha1.NebulaCluster.spec.storaged`

**Comment by wey-gu** [comment]
cc @MegaByte875 @kqzh

**Comment by MegaByte875** [comment]
@jjsimps Please upgrade the crd to 1.3.0.  `kubectl get crd nebulaclusters.apps.nebula-graph.io -o yaml |grep dataVolumeClaims -A 3` to verify.

**Comment by jjsimps** [comment]
Hmmm, I am already on operator 1.3.0. For reference, I upgrade from 1.2.0. Is that enough, or do I need to do something special?

If i take a look at that crd it seems to be the old one (`dataVolumeClaim` not `dataVolumeClaims`).

**Comment by jjsimps** [comment]
https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource

Ah I see, it looks like helm does not upgrade CRDs. Will have to do so manually.

**Comment by wey-gu** [comment]
@MegaByte875 is it feasible/reasonable to hook CRD update when updating operator itself(with helm, or without helm)?

**Comment by kush99993s** [comment]
Hello, 

This happens to new deployments too. I can install the operator. But can't install a cluster using helm.

I tried doing something like 
`helm install "${NEBULA_CLUSTER_NAME}" nebula-operator/nebula-cluster     --namespace="${NEBULA_CLUSTER_NAMESPACE}"     --set nameOverride=${NEBULA_CLUSTER_NAME}     --set nebula.storageClassName="${STORAGE_CLASS_NAME}"`

it throws following error:

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(NebulaCluster.spec.storaged): unknown field "dataVolumeClaims" in io.nebula-graph.apps.v1alpha1.NebulaCluster.spec.storaged`

**Comment by wey-gu** [comment]
Dear @kush99993s,

Welcome to the community!

Could you please help verify the version of operator and the NebulaCluster CRD?

```
# operator
helm list
# crd if supports dataVolumeClaims, which was introduced in 1.3
kubectl get crd nebulaclusters.apps.nebula-graph.io -o yaml |grep dataVolumeClaims -A 3
```

We need to ensure operator is 1.3 and crd is updated to use the yaml in master branch.

We could update crd with:

```bash
kubectl apply -f config/crd/bases/apps.nebula-graph.io_nebulaclusters.yaml
```

**Comment by MegaByte875** [comment]
@wey-gu Upgrade CRD need do it manually,  helm no hooks to support it.

**Comment by wey-gu** [comment]
closing it as it's answered :)
