### ISSUE TITLE
Failed to deploy k8s in huawei cloud

### ISSUE THREAD

**Issue by codingknees** [vesoft-inc/nebula-operator#164]
**General Question**

参考文档，以nubula-operator方式进行部署，环境华为云，k8s版本1.21。
nebula-metad无法启动：
<img width="449" alt="image" src="https://user-images.githubusercontent.com/61698098/195070765-94286ea0-60b9-4510-9458-0f61f441b9f7.png">
pv和pvc状态看起来是正常的：
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/61698098/195071186-d9f2aef2-2e41-4d15-b31c-75b4cf446199.png">
pod的describe信息显示是进程未就绪：
![image](https://user-images.githubusercontent.com/61698098/195071303-e21d9cf1-c867-4ece-a449-728b0279abd5.png)

查看pod中日志文件内容：
0号实例连接2号实例失败
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/61698098/195071424-efeb9f1d-9054-4fbc-8777-0c3cfe520a7c.png">
2号实例未启动，原因是持久化报错：
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/61698098/195071546-d2cb7fbc-d55d-48b6-84cd-6c83883a6230.png">
进入2号实例中，目录挂载路径没问题，读写权限看起来也是正常的：
<img width="480" alt="image" src="https://user-images.githubusercontent.com/61698098/195071841-423f1193-4e69-4b1a-b9af-9f4d9f238a8d.png">

重启pod不能解决这个问题。
请问，我还能如何进一步定位问题，并且进行处理？

**Comment by MegaByte875** [comment]
The problem was fixed in operator 1.3.0.
