### ISSUE TITLE
Use a more clarify phrasing to state out the assigned value `gp2` on k8s property `storageClassName`

### ISSUE THREAD

**Issue by nekomeowww** [vesoft-inc/nebula-operator#169]
**Introduction**

When I trying to deploy `nebula-clutser` with helm, the comment for `storageClassName` states:

> export STORAGE_CLASS_NAME=gp2             # the storage class for the nebula cluster

I think such phrasing mislead me. While such phrasing may be familiar with these operators and developers that are using or have used AWS EBS on or not on K8S, however, I originally thought `gp2` might be some special storgae value that nebula graph has provided for K8S container runtime with the same property name on it when in cluster deployment (since the phrasing says *for nebula clutser*), until I found out this is just the `StorageClass` type value of K8S itself.

**Contents**

We may be able to state out that such value for `storageClassName` will be applied to K8S itself and operators should pick one of the desired and possible value for this property on the demand of themselves instead of just pointing out **it is for the nebula cluster** .

Or I suggest to set the default value to `local` on `storageClassName` in `values.yaml`, and state out the preferences may be made by operators and developers in comments.

**Related work**

None

**Comment by MegaByte875** [comment]
@nekomeowww Thanks for your suggestion, actuallay gp2 is used for eks that runs on aws, if you test nebula in a local development environment, [local](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) is a right configuration. I will update the value to local.

**Comment by nekomeowww** [comment]
Thank you for you reply. I used `local` and it deployed successfully afterwards.

**Comment by QingZ11** [comment]
> Thank you for you reply. I used `local` and it deployed successfully afterwards.

If your problem is solved, would you like to close the issue? Thanks a lot for your contribution.

**Comment by nekomeowww** [comment]
> If your problem is solved, would you like to close the issue? Thanks a lot for your contribution.

Closed.
