### ISSUE TITLE
Additional labels in the helm charts

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula-operator#172]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Below is snippet of line 26 in [nebula-operator](https://github.com/vesoft-inc/nebula-operator)/[charts](https://github.com/vesoft-inc/nebula-operator/tree/master/charts)/[nebula-cluster](https://github.com/vesoft-inc/nebula-operator/tree/master/charts/nebula-cluster)/[templates](https://github.com/vesoft-inc/nebula-operator/tree/master/charts/nebula-cluster/templates)/nebula-cluster.yaml
```
  labels: {{ toYaml .Values.nebula.graphd.podLabels | nindent 6 }}
```

Can someone please take one more look at this?
IMHO, it should be something like following!
```
  labels: {{ toYaml .Values.nebula.storaged.labels.additionalProperties | nindent 6 }}
```

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by MegaByte875** [comment]
@porscheme Is there an error running here?

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.
