### ISSUE TITLE
storagedComponent when Storaged.Service is nil，got panic

### ISSUE THREAD

**Issue by lifetruth-liu** [vesoft-inc/nebula-operator#173]
https://github.com/vesoft-inc/nebula-operator/blob/32e0330370e9a1796378b696e5221cba32ae2e50/apis/apps/v1alpha1/nebulacluster_storaged.go#L174

```go
...
func (c *storagedComponent) GetServiceSpec() *ServiceSpec {
	if c.nc.Spec.Storaged.Service != nil {
		return nil
	}
	return c.nc.Spec.Storaged.Service.DeepCopy()
}
...
```

**Comment by MegaByte875** [comment]
@lifetruth-liu Thanks a lot, I will fix the bug asap.

**Comment by MegaByte875** [comment]
I will close the issue, please re-open it if you have other questions.
