### ISSUE TITLE
Enable Nebula-stats-exporter being deployed as a service

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-operator#184]
Add capabilities to specify sidecar containers, initsidecar Containers and volume containers for exporter. This will help to install promethous agent on exporter pod.

**Comment by wey-gu** [comment]
This was already discussed and planned by @MegaByte875 @MuYiYong and me :). 😁

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/185
