### ISSUE TITLE
Upgrade CRD configuration automatically along with the Operator upgrade.

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula-operator#197]
![image](https://user-images.githubusercontent.com/78209557/231991884-551c366e-7af5-4d07-87d9-9834e610e661.png)

Currently, users need to manually upgrade the CRD configuration after Operator is upgraded. It will be better if the CRD configuration can be upgraded by adding a flag (--set xx) or automatically after Operator is upgraded.

**Comment by wey-gu** [comment]
🧎🏻复议

**Comment by wey-gu** [comment]
impl. via https://github.com/vesoft-inc/nebula-operator/pull/395
