### ISSUE TITLE
unable to install nebula-operator on on-premise Rancher v17.17

### ISSUE THREAD

**Issue by norcal230** [vesoft-inc/nebula-operator#20]
I am receiving the below error but not sure how to resolve this error.

"transitioning": "error",
"transitioningMessage": "failed to install app nebula-operator. Error: unable to build kubernetes objects from release manifest: [unable to recognize \"\": no matches for kind \"Certificate\" in version \"cert-manager.io/v1\", unable to recognize \"\": no matches for kind \"Issuer\" in version \"cert-manager.io/v1\"]",

**Comment by wey-gu** [comment]
Dear @norcal230 
I guess it's caused by missing 3pp dependency: CertManager, right?
Thanks.

**Comment by norcal230** [comment]
Yes.  That was the issue.  I got diverted to another pressing project but should be able to finish testing the operator soon.    Thank you for the follow up.  

Thanks!
