### ISSUE TITLE
Exporter does not work on k8

### ISSUE THREAD

**Issue by jjsimps** [vesoft-inc/nebula-operator#200]
**Describe the bug (__required__)**

The exporter functionality runs, but it is not able to scrape any of the metrics properly.

In the logs, I see:

```
I0524 19:15:24.091498       1 exporter.go:91] Start collect
E0524 19:15:24.096177       1 exporter.go:223] pods is forbidden: User "system:serviceaccount:core-dev:default" cannot list resource "pods" in API group "" in the namespace "core-dev"
I0524 19:15:24.096203       1 exporter.go:93] Complete collect, time elapse 4.715559ms
```

It seems like the Roles/ServiceAccount/RolesBinding etc are not generated properly. They do exist in the original nebula-exporter chart.

**Your Environments (__required__)**

Running on k8, chart version 1.4.2 (latest)

**How To Reproduce(__required__)**

Enabled exporter with default settings, 1 replica.

**Expected behavior**

No errors in the logs and the exporter to have metric values.

**Comment by wey-gu** [comment]
Thanks @jjsimps , could you @MegaByte875 please take a look at the `Roles/ServiceAccount/RolesBinding` genration for monitoring function of the operator?

**Comment by MegaByte875** [comment]
@wey-gu The error is "list pods" role lost. Let me check it.
