### ISSUE TITLE
scale failed without log config

### ISSUE THREAD

**Issue by veezhang** [vesoft-inc/nebula-operator#208]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/212
