### ISSUE TITLE
should transfer leader concurrently when update configuration

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula-operator#219]
when  update storage configuration, it would be rolling update the storage pod.
but transfer the leader part by part, and it would be a long time for some queries, e.g. 

```
match (v) return v limit 10

```

expected:
1. transfer leader concurrently.

**Comment by kqzh** [comment]
I try to transfer leader concurrently, but get many errors  cc @HarrisChu @MegaByte875 

![image](https://github.com/vesoft-inc/nebula-operator/assets/35095889/0f430234-5756-4d85-9931-9e3c6fe83d74)
![image](https://github.com/vesoft-inc/nebula-operator/assets/35095889/c99647b8-55a4-45d5-9481-3ec6a12accd3)

**Comment by HarrisChu** [comment]
please check if multiple go routines use the same tcp connection.

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/255

**Comment by jinyingsunny** [comment]
development students selftest，sc not use it
