### ISSUE TITLE
when enabled logrotate，timestamp_in_logfile_name should be false

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#228]
because，when timestamp_in_logfile_name = true，new generated log with new timestamp in name, so it will never
the same, so it can not rotate.
with `timestamp_in_logfile_name =true`, log listed as follow picture:
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/d674cb6e-d645-4c25-997f-f15602771950)

contact with kevin.qiao, let remind user to set timestamp_in_logfile_name=false in doc ,thx @abby-cyber 

**Your Environments (__required__)**

nebulaOperator:
image: reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.4
nebula:
image: reg.vesoft-inc.com/rc/nebula-graphd-ent:v3.5.0-sc
agent:
image: reg.vesoft-inc.com/cloud-dev/nebula-agent:v3.5.1

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/2932
