### ISSUE TITLE
[k8s] br backup‘s generated job-name and pod-name ，can with name consisted with the backup cluster？

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#230]
**Please check the FAQ documentation before raising an issue**
k8s中在ns nebula下有两个nebula集群，nebula 和 通过做br备份产生的集群ngxvsm，当针对集群 ngxvsm再来做备份的时候：
当前备份的job名称是：nebula-full-backup ；
生成的pod名称是nebula-full-backup-nr9r5 ：
（full-backup 是yaml文件的名称，nr9r5 是随机串，前缀是nebula有些奇怪，因为档期备份的集群是 ngxvsm）

可以把备份产生的pod名字以 当前备份的集群（ngxvsm）作为前缀不？
可以把备份产生的job名字，以当前备份的集群（ngxvsm）作为前缀不？

```
root@k8s-master:/home/sunny.liu/k8s_file/br_bakeup# kubectl -n nebula  get nc
NAME     GRAPHD-DESIRED   GRAPHD-READY   METAD-DESIRED   METAD-READY   STORAGED-DESIRED   STORAGED-READY   AGE
nebula   1                1              1               1             3                  3                4d3h
ngxvsm   1                1              1               1             3                  3                5d6h 

root@k8s-master:/home/sunny.liu/k8s_file/br_bakeup# kubectl -n nebula  get jobs
NAME                 COMPLETIONS   DURATION   AGE
nebula-full-backup   1/1           6s         17s
```

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/685239bb-87fe-48a0-910e-b81325a3f7f2)

**Your Environments (__required__)**

nebula-ent-sc-rc包
镜像是：
image: reg.vesoft-inc.com/rc/nebula-storaged-ent
version: v3.5.0-sc
operator镜像是：
reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.4

**How To Reproduce(__required__)**

**Comment by MegaByte875** [comment]
1st question: The pod name is generated from job, I can't modify it.  
2nd question:  The job name can be modified at any time, it's not generated by nebula-opeartor.

**Comment by jinyingsunny** [comment]
OK closed.
