### ISSUE TITLE
Unable to execute perf in k8s pods

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-operator#254]
**Linux Version
uname -a
Linux xxxx-graphd-8 5.10.184-174.730.amzn2.x86_64 #1 SMP Mon Jun 19 02:03:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux**

![Image](https://github.com/vesoft-inc/nebula-operator/assets/19355821/251f0abe-b80e-4cb0-bba6-4ec1b86d9f81)

## 首先解决安装perf的问题
`apt install linux-tools-generic`

直接跑perf会遇到错误`perf not found for kernel 5.10.184`

接下来删掉/usr/bin/perf，然后创建软链接 (具体版本依实际情况而定)
`ln -s /usr/lib/linux-tools/5.4.0-110-generic/perf /usr/bin/perf`

Ref: https://askubuntu.com/questions/50145/how-to-install-perf-monitoring-tool
```
On ubuntu "perf" is a shell script that calls a kernel specific perf binary.

But that's not actually needed, perf is compatible. Just remove the wrapper from /usr/bin and copy any of the perf binaries from ./lib/linux-tools* to it.
```

**Comment by wenhaocs** [comment]
接下来运行perf遇到以下问题：


![Image](https://github.com/vesoft-inc/nebula-operator/assets/19355821/45727717-97c7-4e66-94c7-a8452dcaa245)

Trying to alter the suggested /proc/sys/kernel/perf_event_paranoid from within the container gets you the expected:

![Image](https://github.com/vesoft-inc/nebula-operator/assets/19355821/c5b458de-3aff-4313-a6b9-4a9a508ea5fb)


可能得解决方法：
https://blog.alicegoldfuss.com/enabling-perf-in-kubernetes/

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/257

**Comment by wenhaocs** [comment]
With the fix, running `perf` will show the following warnings:

![Image](https://github.com/vesoft-inc/nebula-operator/assets/19355821/9239f3be-48d8-42a3-9180-bf1ff09aff0e)

32.16%的kernel不显示具体信息

![Image](https://github.com/vesoft-inc/nebula-operator/assets/19355821/ccdb232a-8d7c-4d36-b25f-354902f2b430)

**Comment by wenhaocs** [comment]
尝试在/etc/sysct.conf中添加 kernel.perf_event_paranoid = -1 ，运行sysctl --system

![Image](https://github.com/vesoft-inc/nebula-operator/assets/19355821/aed0b9c8-b700-4814-ae94-c55a796d84ec)

**Comment by MegaByte875** [comment]
# 添加运行 perf 的设置
$ kubectl patch statefulset statefulset <statefulset-name> -n <namespace> --patch '{"spec": {"template": {"spec": {"initContainers": [{"name": "systctl", "securityContext": {"privileged": true}, "image": "busybox", "command": ["sh", "-c", "sysctl -w kernel.perf_event_paranoid=-1"]}],"containers": [{"name": "graphd","securityContext": {"capabilities": {"add": ["SYS_ADMIN"]}}}]}}}}'
 
# 还原设置
$ kubectl patch statefulset statefulset <statefulset-name> -n <namespace> --patch '{"spec": {"template": {"spec": {"initContainers": [{"name": "systctl", "$patch":"delete"}],"containers": [{"name": "graphd","securityContext": {"capabilities": {"add": ["SYS_ADMIN"]}}}]}}}}'

**Comment by MegaByte875** [comment]
`kubectl patch statefulset <statefulset-name> -n <namespace>  --patch '{"spec": {"template": {"spec": {"containers": [{"name": "graphd","securityContext": {"privileged": true}}]}}}}'`

<img width="934" alt="image" src="https://github.com/vesoft-inc/nebula-operator/assets/4974026/46e02d37-d2ff-42c4-924b-9e69ecf42953">

**Comment by wenhaocs** [comment]
Since the whole cluster will restart and it's not safe to raise the privilege in all containers, please only enable this function in staging cluster for debugging purpose.
