### ISSUE TITLE
HPA support for graphd

### ISSUE THREAD

**Issue by xiajingchun** [vesoft-inc/nebula-operator#264]
From customer:

> Theortically Graphd is a stateless service. But in k8s setup it is still desgined as statefulset… So ideally this can be migrated to Deployment rather than statefulset. But this can be done as a separate task.
> 
>  
> 
> The ask here is to enable HPA for graphd… I don’t see it currently being supported in nebula operator. 
> 
> https://github.com/vesoft-inc/nebula-operator/blob/v1.5.0/charts/nebula-cluster/templates/nebula-cluster.yaml#L10C51-L10C51

**Comment by wenhaocs** [comment]
Please consider scaling with CPU resource only for the first release.

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/302
