### ISSUE TITLE
cannot scale out the storage replica with zone

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula-operator#269]
![image](https://github.com/vesoft-inc/nebula-operator/assets/1726587/36b79ca9-afd1-4cb8-a545-4e2ecbc1b760)

can not add hosts successfully.

**Comment by jinyingsunny** [comment]
申请pvc比较慢，申请完，🈶️过了30分钟才看到扩容成功。

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/277
