### ISSUE TITLE
helm install nebula cluster

### ISSUE THREAD

**Issue by veezhang** [vesoft-inc/nebula-operator#27]

**Comment by wey-gu** [comment]
Cool!

Does this mean we will have a helm chart based on nebula cluster CRD? 

And one helm install will help install all 3pp dependencies as well?

**Comment by veezhang** [comment]
@wey-gu It's just for install nebula cluster CRD with helm chart.  

And the dependencies need to install manually according to the documentation [install guide](https://github.com/vesoft-inc/nebula-operator/blob/master/doc/user/install_guide.md).

**Comment by wey-gu** [comment]
> @wey-gu It's just for install nebula cluster CRD with helm chart.
> 
> And the dependencies need to install manually according to the documentation [install guide](https://github.com/vesoft-inc/nebula-operator/blob/master/doc/user/install_guide.md).

Got it @veezhang , thanks, but as I recall to install nebulaCluster CRD itself via helm chart is already what you had provided, this issue was opened only for marking the implemented task? or?

**Comment by veezhang** [comment]
@wey-gu  What you mentioned is the feature to install nebula operator with helm. And this issue is for install nebula cluster managed by nebula operator.

**Comment by wey-gu** [comment]
> @wey-gu What you mentioned is the feature to install nebula operator with helm. And this issue is for install nebula cluster managed by nebula operator.

Thank you @veezhang , now I understand it! This is extra cool!
