### ISSUE TITLE
Update the dynamic flags with recent zone features and session related fix

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-operator#282]
Potential dynamic flags:

prioritize_intra_zone_reading
stick_to_intra_zone_on_failure
sync_meta_when_use_space
validate_session_timestamp

Please update https://confluence.nebula-graph.io/pages/viewpage.action?pageId=72586840 as well

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/305

**Comment by jinyingsunny** [comment]
https://github.com/vesoft-inc/nebula-operator/issues/315 prioritize_intra_zone_reading是一个控制变量，用来加载init-container node-labels，因此变更后必须重启pod，无法做成动态参数！
