### ISSUE TITLE
Fix the release process of Operator

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-operator#290]
`Error: INSTALLATION FAILED: chart "nebula-operator" matching 1.6.2 not found in nebula-operator index. (try 'helm repo update'): no chart version found for nebula-operator-1.6.2`

Apparently, the chart index does not have 1.6.2 yet.

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/292
