### ISSUE TITLE
Wrong binaries in arm64 version of the docker images for nebula-operator

### ISSUE THREAD

**Issue by svok** [vesoft-inc/nebula-operator#308]
**Describe the bug (__required__)**

Docker image for linux/arm64 platform of the vesoft/nebula-operator:v1.6.3 at Docker Hub contains x86_64 (AMD64) binaries.

**Your Environments (__required__)**

* OS: `Linux op1 5.10.110-rockchip-rk3588 #1.0.2 SMP Thu Apr 13 16:55:55 CST 2023 aarch64 aarch64 aarch64 GNU/Linux`
* Docker Image ID:  8cb85d69068e

**How To Reproduce(__required__)**

I'm trying to run nebula-operator on the ARM64 Kubernetes platform.
As I start 
```bash
helm install nebula-operator nebula-operator/nebula-operator --namespace=nebula-operator-system --version=1.6.3
```
I get in the logs the following errors for both `nebula-operator-controller-manager-deployment` and `nebula-operator-scheduler-deployment`:
> exec /usr/local/bin/controller-manager: exec format error

That's all. It is not working.

I pulled image `vesoft/nebula-operator:v1.6.3` (8cb85d69068e) and checked its content. This is the description of the /bin/sh file:
```
root@op1:/home/orangepi/work# readelf -h sh
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Position-Independent Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x85f1
  Start of program headers:          64 (bytes into file)
  Start of section headers:          815352 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         11
  Size of section headers:           6**Additional context**
```

The `controller-manager` file is also specified as `Advanced Micro Devices X86-64`.

**Expected behavior**

The container for platform arm64 must contain correct ARM64 binaries rather then AMD64

**Comment by MegaByte875** [comment]
@svok Thanks a lot. I've fixed the issue, please try again.

**Comment by svok** [comment]
Thank you @MegaByte875. I confirm, installation's done

**Comment by svok** [comment]
Unfortunately, I've found one more image with wrong platform.
vesoft/nebula-stats-exporter:v3.3.0

**Comment by MegaByte875** [comment]
@svok Ok, I will fixed them asap.

**Comment by svok** [comment]
The next iteration and one more step futher.
vesoft/nebula-stats-exporter:v3.3.0 - the same problem.

**Comment by svok** [comment]
Since 1.7.0 vesoft/nebula-stats-exporter is not required anymore. Both nebula-operator and nebula-cluster have been installed successfully. Thank you.
