### ISSUE TITLE
httpPort allow change, however modify grapd operator report error 

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#318]
it seam's changed httpPort succeed ,but operator report some error msg: 
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/6cf3f645-7753-444f-a249-7c3fea6a651d)
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/c0ab8786-a545-4ff0-83e3-554697c28532)
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/e847dd7a-d894-4d79-b627-9f88a0522e86)

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/e6ec0af3-94a3-4087-a0b9-2238717947ca)

```
E1009 07:53:28.356215       1 nebula_cluster_control.go:134] reconcile graphd cluster failed: update graphd cluster nebulazone-graphd dynamic flags failed: get http://nebulazone-graphd-0.nebulazone-graphd-headless.nebula.svc.cluster.local:1967/9/flags response body is empty
```

**Your Environments (__required__)**

nebula-operator: snap-1.19

**How To Reproduce(__required__)**

```
1.打patch的命令
kubectl -n nebula patch nc nebulazone  --type='merge' --patch='{"spec": {"graphd": {"httpPort":19679}}}' 

2.查看结果
kubectl -n nebula describe nc nebulazone |grep graphd -C 10
kubectl -n nebula get service
kubectl -n nebula get pod

3.跟踪operator日志
kubectl -n nebula-operator-system logs -f nebula-operator-controller-manager-deployment-6677c5c74f-gpvcf
 ```

**Expected behavior**

no error msg

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/319

**Comment by jinyingsunny** [comment]
nebula-operator: snap-1.21 checked ok!
