### ISSUE TITLE
ngctl cmd tool 

### ISSUE THREAD

**Issue by MegaByte875** [vesoft-inc/nebula-operator#32]
ngctl is a terminal cmd tool for nebula-operator, it has the following functions:

-  debug   // debug a container in the specified pod
-  console // establish a connection to graphd
-  list  // list all nebulaclusters
-  cluster-info // print cluster details, contains component status, resources, image versions etc.
-  version // print git commit info

**Comment by wey-gu** [comment]
I am so very excited about ngctl, looking forward to it!

Hopefully to also have it wrapped in lifecycle management(scaling, update)/ BR in the future!

**Comment by kqzh** [comment]
we can also use [krew](https://github.com/kubernetes-sigs/krew) to make ngctl be a kubectl plugin. It's easier to find and install
