### ISSUE TITLE
Upgrade CRD automatically

### ISSUE THREAD

**Issue by MegaByte875** [vesoft-inc/nebula-operator#332]
**Introduction**

We hope apply CRD autotically while upgrade operator to new version.

**Contents**

**Related work**

**Comment by wey-gu** [comment]
FINALLY 🚀!!!!

ref https://github.com/vesoft-inc/nebula-operator/issues/197

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/395
