### ISSUE TITLE
Internal optimization

### ISSUE THREAD

**Issue by MegaByte875** [vesoft-inc/nebula-operator#337]
**Introduction**

- [x] Add finalizer
- [x] Add event output to help locate faults quickly

**Contents**

**Related work**

**Comment by veezhang** [comment]
It's need delete pvcs and then remove the finalizer.

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/409

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/411
