### ISSUE TITLE
Scale down graphd & storaged by distributing the node shutdowns evenly across all zones

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-operator#351]
In addition, what should we do when scaling down is performed and storaged nodes are already imbalanced across zones?

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/issues/341

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/369
