### ISSUE TITLE
How to Run Containers as a Non-root User 

### ISSUE THREAD

**Issue by hpfish** [vesoft-inc/nebula-operator#371]
**General Question**
How to Run Containers as a Non-root User?

**Comment by MegaByte875** [comment]
Can you describe it in more detail？

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
