### ISSUE TITLE
after restart a storaged pod ,part not even

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#422]
as title. when restart a storage pod：
```
# kubectl -n nebula annotate sts nebula2-storaged nebula-graph.io/restart-ordinal="1"
statefulset.apps/nebula2-storaged annotate 
```

transfer leader to storaged0( when restart storaged1 ,leader will transfer to storaged0;when restart storaged0 ,leader will transfer to storaged2)
```
I0124 10:55:11.244751       1 meta_client.go:326] space 1 partition 97 leader still on this node
....
I0124 10:55:11.249970       1 storage_client.go:86] start transfer leader spaceID 1 partitionID 97
I0124 10:55:11.252876       1 storaged_updater.go:389] storaged cluster [nebula/nebula2-storaged] transfer leader spaceID 1 partitionID 99 to host nebula2-storaged-0.nebula2-storaged-headless.nebula.svc.cluster.local successfully
```

show jobs without balance leader. so parts separated on storage0 and storage1 ,not even
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/f45394de-3c29-45ed-80be-537bd19da57a)

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/0313c71d-8f55-4da7-a1d4-031f1408bca5)

**Your Environments (__required__)**

operator:snap-1.30

**Expected behavior**

leader become even at last

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/435

**Comment by jinyingsunny** [comment]
用nebula-operator:snap-1.34验证，依旧有上面的问题

**Comment by jinyingsunny** [comment]
经过修复，用nebula-operator:snap-1.35验证，after storaged pod restart, it do `balance leader`, but storage leader still not even .
closed this issue , followed up with new issue https://github.com/vesoft-inc/nebula-operator/issues/443
