### ISSUE TITLE
when restart metad cluster without transfer meta leader

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#423]
as title.when 3 metad restart one after another, meta leader keep on metad1. 
during the restart time, some action ,which need to contact with meta leader ,may be failed.
```
# 获取时间戳
$ date -u +%s
1706083832 

# 覆盖初始时间戳触发meta组件滚动重启
$ kubectl -n nebula annotate sts nebula2-metad nebula-graph.io/restart-timestamp="1706083832" --overwrite 


# 观察重启事件 $ kubectl -n nebula get pod
nebula2-console 1/1 Running 0 42m
nebula2-exporter-5d5d6f5455-7r842 1/1 Running 0 58m
nebula2-graphd-0 1/1 Running 0 41m
nebula2-graphd-1 1/1 Running 0 41m
nebula2-graphd-2 1/1 Running 0 42m
nebula2-metad-0 1/1 Running 0 58m
nebula2-metad-1 0/1 ContainerCreating 0 0s
nebula2-metad-2 1/1 Running 0 42s
nebula2-storaged-0 1/1 Running 0 9m59s
nebula2-storaged-1 1/1 Running 0 7m31s
nebula2-storaged-2 1/1 Running 0 10m
```
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/31c08476-0cc7-47e9-8224-80d91cc742d2)

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/6c544b86-d5f1-4441-91a1-019f43417748)

**Your Environments (__required__)**

operator:snap-1.30

**Expected behavior**

before restart meta leader pod , please transfer meta leader to another metad pod.

**Comment by MegaByte875** [comment]
Metad not provide tranfer leader interface.

**Comment by wenhaocs** [comment]
Agree. If there is no ongoing schema change, graphd and storaged will only send heartbeat to metad, which can endure failovers for some time.  There are only 3 metad for any cluster, and the restarting process should be quick. Further, chances of restarting metad is very rare. I suggest to keep what it is for now.

**Comment by jinyingsunny** [comment]
ok, mark as known issue.
