### ISSUE TITLE
after restart storage cluster, why we `balance leader` for many times

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#424]
the follow picture show ,after restart 3 storaged-cluster, during 10 seconds, `balance leader` execute for 9 times.
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/199f3077-4697-4df6-a48f-34b21fa16412)

operator log:
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/2da39a80-f52e-4f7a-a20f-4a62202c4f3f)

触发场景：
```
metad、graphd、storage三个组件 一起滚动，提交的顺序是：storaged->graphd->metad。实际看现象是：meta先执行(meta2-meta1-meta0),然后执行storage(storage2-storage1-storage0),最后执行graph(graphd2->graphd1->graphd0)

root@k8s-master:/home/sunny.liu/k8s_file# kubectl -n nebula annotate sts nebula2-storaged nebula-graph.io/restart-timestamp="1706087297" --overwrite
statefulset.apps/nebula2-storaged annotate

root@k8s-master:/home/sunny.liu/k8s_file# kubectl -n nebula annotate sts nebula2-graphd nebula-graph.io/restart-timestamp="1706087297" --overwrite
statefulset.apps/nebula2-graphd annotate

root@k8s-master:/home/sunny.liu/k8s_file# kubectl -n nebula annotate sts nebula2-metad nebula-graph.io/restart-timestamp="1706087297" --overwrite
statefulset.apps/nebula2-metad annotate 
```
只有第一笔是storaged没ready，后面就都说是graphd 没ready了
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/8272f537-33ee-47b1-a204-81c417711c45)

another question：when restart storage cluster, why we balance leader twice? 
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/63560f5d-c5f1-456c-a0a0-854192a47c6a)

**Your Environments (__required__)**

operator:snap-1.30

**Expected behavior**

execute `balance leader` once

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/435

**Comment by jinyingsunny** [comment]
用operator:snap-1.35 check，已经不再做多次。

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/89779982-ee48-4d0d-8111-820857a8f20f)
相应的日志：
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/0e9e8b58-f08b-4d7d-8ba5-bf2989d5a997)
