### ISSUE TITLE
restore sf100 job failed, actually succeed

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#460]
as title
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/bd96d61b-47c9-488d-a426-734fd35593b0)

用console连新创建的集群。数据也已经到位
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/d3d6b116-c95a-4304-91d8-b20d55edb1d5)

**Your Environments (__required__)**

operator镜像：reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.39

**How To Reproduce(__required__)**

restore sf100‘s cluster 

**Expected behavior**

restore job‘s status is complete

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/461

**Comment by jinyingsunny** [comment]
checked on snap-1.42, after several time failed ,finally completed
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/95b8ba5a-c41a-433f-91d1-c0fd4b3e7620)
