### ISSUE TITLE
in aws, when do restore, restart metad too many times

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#462]
normally, restart once is ok 

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/6f5d4af9-e970-4da8-87e5-12d15a27cd5a)

**Your Environments (__required__)**

```
operator：reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.41
br-ent: reg.vesoft-inc.com/cloud-dev/br-ent:v3.7.0
agent: reg.vesoft-inc.com/cloud-dev/nebula-agent:snap
nebula: reg.vesoft-inc.com/qa/nebula-graphd-ent:snap-hotfix
nebula: reg.vesoft-inc.com/qa/nebula-metad-ent:snap-hotfix
nebula: reg.vesoft-inc.com/qa/nebula-storaged-ent:snap-hotfix
```
**How To Reproduce(__required__)**

do restore

**Expected behavior**

restart once ,and begin storage restore

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/464

**Comment by jinyingsunny** [comment]
checked operator：snap-1.42
