### ISSUE TITLE
storaged  pod pending when restore cluster in GKE

### ISSUE THREAD

**Issue by MegaByte875** [vesoft-inc/nebula-operator#491]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
![image](https://github.com/vesoft-inc/nebula-operator/assets/4974026/a1ea0739-7b8e-46ad-9d44-1102ba33e31e)
![image](https://github.com/vesoft-inc/nebula-operator/assets/4974026/7d796ec6-6eee-4e52-971d-1c18b5b34a18)
After the nodes scaled ready, the pending pod didn't scheduled to the new nodes. 

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**
The pending storaged pod scheduled to new nodes.

**Additional context**

**Comment by jinyingsunny** [comment]
这个storaged0的没有下载数据，是因为其他节点上pending，没都ready，所以没下发拉取数据 的命令；
但是当其他节点后续ready后，也没有触发拉取数据的命令，是手动删除 storaged-0后重新触发的

**Comment by MegaByte875** [comment]
<img width="738" alt="image" src="https://github.com/vesoft-inc/nebula-operator/assets/4974026/6f1e7861-90ca-4e75-a615-9b2096c40fd7">

```
 --pod-max-in-unschedulable-pods-duration duration                                                                                                                                                   
  DEPRECATED: the maximum time a pod can stay in unschedulablePods. If a pod stays in unschedulablePods for longer than this value, the pod will be moved from unschedulablePods to backoffQ or
                activeQ. This flag is deprecated and will be removed in 1.26 (default 5m0s)
```

**Comment by MegaByte875** [comment]
The normal events:
```
Events:
  Type     Reason            Age   From                Message
  ----     ------            ----  ----                -------
  Warning  FailedScheduling  10s   nebula-scheduler    0/11 nodes are available: 4 Insufficient cpu, 7 node(s) didn't match Pod's node affinity/selector. preemption: 0/11 nodes are available: 4 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling..
  Normal   TriggeredScaleUp  7s    cluster-autoscaler  pod triggered scale-up: [{https://www.googleapis.com/compute/v1/projects/vesoft-public-405209/zones/us-central1-c/instanceGroups/gke-snap-test-sk1-4c81a7ee-grp 1->2 (max: 2)}]
```

**Comment by MegaByte875** [comment]
The nebula-scheduler can't drive CA to scale up node in a specific zone. So I need optimize operator to support the scenario.

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/495
