### ISSUE TITLE
NA minReplica maxReplica validation

### ISSUE THREAD

**Issue by MegaByte875** [vesoft-inc/nebula-operator#500]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

If minReplica > maxReplica , apply does not raise error,  a few instances of graphd  will cycle between being created and terminating state.  Proposing adding a validation logic.

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by kevinliu24** [comment]
Design page:
https://nebula-graph.atlassian.net/wiki/spaces/TDEV/pages/149094404/Admissions+Webhook+for+Autoscaler+and+Passing+Cert+via+Sidecar

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/502
