### ISSUE TITLE
more readable pvc name

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula-operator#60]
![image](https://user-images.githubusercontent.com/1726587/132618730-175caaf6-9de7-43be-aadb-e3e4b0c7c571.png)

`graphd-bdrpgh-graphd-0`

maybe  `bdrpgh-graphd-0` is more clearly? If I have multiple nebulacluster, it is sorted by `graphd`.

**Comment by MegaByte875** [comment]
The pvc names are generated by statefulset controller，the naming rule is <pvc.name>-<statefulset.name>-<ordinal>.  @HarrisChu
