### ISSUE TITLE
why the nebulacluster setup up slowly

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula-operator#61]
![image](https://user-images.githubusercontent.com/1726587/132787461-eb579cd4-4328-4168-ac75-c875c0160434.png)

![image](https://user-images.githubusercontent.com/1726587/132787438-8b0514bf-fa36-4e3e-bd7d-de799d5ac5d8.png)

**Comment by HarrisChu** [comment]
```
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```
could I modify this readinessProbe in nebulacluster resource?

**Comment by MegaByte875** [comment]
The readinessProbe configuration will expose to users in verison v0.9.0

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/83
