### ISSUE TITLE
期望helm安装能支持config选项 

### ISSUE THREAD

**Issue by zdz1715** [vesoft-inc/nebula-operator#73]
自定义资源上支持修改config，但helm模板并没有支持config选项，期望能加上
![微信图片_20210923181619](https://user-images.githubusercontent.com/24859074/134490756-530d2552-b7c4-4654-9e51-b821ba23a6e9.png)

**Comment by MegaByte875** [comment]
We will provide the feature in v0.9.0 recently, please wait for days.

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/81 @zdz1715
