### ISSUE TITLE
cluster upgrade failure

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula-operator#87]
when I upgrade a cluster from v2.0.1 to v v2.6.1，after waiting for about 10m,  it didn't work.

![image](https://user-images.githubusercontent.com/78209557/140935288-656091b2-238a-44a0-afc0-7872e5042500.png)

ran `kubectl describe nc nebula`, showing
![image](https://user-images.githubusercontent.com/78209557/140935467-83fc4c47-7825-4907-8a1f-765ba402f070.png)

**Comment by MegaByte875** [comment]
nebula-operator doesn't support v2.0.x upgrade to v2.6.x.
